'use client'
import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import type { Animal } from '@/lib/types'

const DOC_TYPES = [
  {
    id: 'movement_permit',
    label: 'Movement permit',
    desc: 'Required to transport any animal between parishes',
    color: 'text-blue-400',
    border: 'border-blue-500/20',
    bg: 'bg-blue-500/5',
    activeBg: 'bg-blue-500/10',
  },
  {
    id: 'sale_certificate',
    label: 'Sale certificate',
    desc: 'Legal proof of ownership transfer',
    color: 'text-green-400',
    border: 'border-green-500/20',
    bg: 'bg-green-500/5',
    activeBg: 'bg-green-500/10',
  },
  {
    id: 'health_declaration',
    label: 'Health declaration',
    desc: 'Certifies animal is fit for transport or sale',
    color: 'text-purple-400',
    border: 'border-purple-500/20',
    bg: 'bg-purple-500/5',
    activeBg: 'bg-purple-500/10',
  },
]

export default function DocumentsPage() {
  const [animals, setAnimals] = useState<Animal[]>([])
  const [selectedAnimal, setSelectedAnimal] = useState('')
  const [selectedDoc, setSelectedDoc] = useState('')
  const [generating, setGenerating] = useState(false)
  const [document, setDocument] = useState('')
  const [docTitle, setDocTitle] = useState('')
  const [error, setError] = useState('')

  useEffect(() => {
    supabase.from('animals').select('*').order('name')
      .then(({ data }) => { if (data) setAnimals(data) })
  }, [])

  async function generateDocument() {
    if (!selectedAnimal || !selectedDoc) {
      setError('Select an animal and document type')
      return
    }
    setError('')
    setGenerating(true)
    setDocument('')

    try {
      const res = await fetch('/api/documents', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tag_id: selectedAnimal, document_type: selectedDoc }),
      })
      const data = await res.json()
      if (data.success) {
        setDocument(data.content)
        setDocTitle(DOC_TYPES.find(d => d.id === selectedDoc)?.label || '')
      } else {
        setError(data.error || 'Failed to generate')
      }
    } catch {
      setError('Network error — try again')
    }
    setGenerating(false)
  }

  function printDocument() {
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(`
      <html>
        <head>
          <title>${docTitle} — LiveStack</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.7; color: #111; }
            pre { white-space: pre-wrap; font-family: Arial, sans-serif; font-size: 13px; }
            h2 { color: #166534; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
            @media print { .no-print { display: none; } }
          </style>
        </head>
        <body>
          <h2>LiveStack — ${docTitle}</h2>
          <pre>${document}</pre>
          <div class="footer">Generated by LiveStack Digital Registry · Praedial Larceny Prevention Act 2023</div>
          <br/>
          <button class="no-print" onclick="window.print()" style="background:#166534;color:white;border:none;padding:10px 20px;border-radius:8px;cursor:pointer;font-size:13px;">
            Print / Save as PDF
          </button>
        </body>
      </html>
    `)
    win.document.close()
  }

  return (
    <div className="min-h-screen bg-black text-white">

      {/* Header */}
      <header className="border-b border-white/10 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <a href="/" className="flex items-center gap-2 hover:opacity-70 transition-opacity">
              <div className="w-7 h-7 bg-green-500 rounded-lg flex items-center justify-center">
                <div className="w-2.5 h-2.5 bg-black rounded-full animate-pulse" />
              </div>
              <span className="font-bold text-sm">LiveStack</span>
            </a>
            <span className="text-white/20">/</span>
            <span className="text-white/60 text-sm">Documents</span>
          </div>
          <div className="flex items-center gap-2">
            <a href="/dashboard" className="text-xs border border-white/10 hover:border-white/20 px-3 py-1.5 rounded-lg text-white/60 hover:text-white transition-all">Dashboard</a>
            <a href="/map" className="text-xs border border-white/10 hover:border-white/20 px-3 py-1.5 rounded-lg text-white/60 hover:text-white transition-all">Map</a>
            <a href="/health" className="text-xs border border-white/10 hover:border-white/20 px-3 py-1.5 rounded-lg text-white/60 hover:text-white transition-all">Health</a>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">

        <div className="mb-8">
          <h1 className="text-2xl font-black tracking-tight">RADA Documents</h1>
          <p className="text-white/40 text-sm mt-1">AI-generated livestock papers · Praedial Larceny Prevention Act 2023</p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">

          {/* Left — controls */}
          <div className="space-y-4">

            {/* Animal selector */}
            <div className="bg-white/5 border border-white/10 rounded-2xl p-5">
              <div className="text-xs font-medium text-white/30 uppercase tracking-wider mb-3">
                Select animal
              </div>
              <select
                value={selectedAnimal}
                onChange={e => setSelectedAnimal(e.target.value)}
                className="w-full bg-white/5 border border-white/10 text-white text-sm rounded-xl px-4 py-3 focus:outline-none focus:border-white/20 transition-colors"
              >
                <option value="">Choose an animal...</option>
                {animals.map(a => (
                  <option key={a.tag_id} value={a.tag_id}>
                    {a.name} — {a.tag_id} · {a.breed}
                  </option>
                ))}
              </select>
            </div>

            {/* Doc type selector */}
            <div className="bg-white/5 border border-white/10 rounded-2xl p-5">
              <div className="text-xs font-medium text-white/30 uppercase tracking-wider mb-3">
                Document type
              </div>
              <div className="space-y-2">
                {DOC_TYPES.map(doc => (
                  <div
                    key={doc.id}
                    onClick={() => setSelectedDoc(doc.id)}
                    className={`border rounded-xl p-4 cursor-pointer transition-all ${
                      selectedDoc === doc.id
                        ? `${doc.activeBg} ${doc.border} border`
                        : 'border-white/10 hover:border-white/20 bg-white/5'
                    }`}
                  >
                    <div className={`font-medium text-sm mb-0.5 ${selectedDoc === doc.id ? doc.color : 'text-white'}`}>
                      {doc.label}
                    </div>
                    <div className="text-xs text-white/30">{doc.desc}</div>
                  </div>
                ))}
              </div>
            </div>

            {error && (
              <div className="bg-red-500/5 border border-red-500/20 rounded-xl p-3 text-sm text-red-400">
                {error}
              </div>
            )}

            <button
              onClick={generateDocument}
              disabled={generating || !selectedAnimal || !selectedDoc}
              className="w-full bg-green-500 hover:bg-green-400 disabled:opacity-30 disabled:cursor-not-allowed text-black font-bold py-4 rounded-xl transition-colors"
            >
              {generating ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin"></span>
                  Claude is writing...
                </span>
              ) : 'Generate document'}
            </button>
          </div>

          {/* Right — preview */}
          <div className="bg-white/5 border border-white/10 rounded-2xl overflow-hidden flex flex-col min-h-96">
            {!document && !generating && (
              <div className="flex-1 flex flex-col items-center justify-center p-10 text-center">
                <div className="w-14 h-14 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center mb-4">
                  <span className="text-white/20 text-2xl">◇</span>
                </div>
                <p className="text-white/40 text-sm font-medium">No document yet</p>
                <p className="text-white/20 text-xs mt-1">
                  Select an animal and type, then generate
                </p>
              </div>
            )}

            {generating && (
              <div className="flex-1 flex flex-col items-center justify-center p-10">
                <div className="w-8 h-8 border-2 border-green-500 border-t-transparent rounded-full animate-spin mb-4"></div>
                <p className="text-white/40 text-sm">Claude is writing your document...</p>
              </div>
            )}

            {document && !generating && (
              <div className="flex flex-col h-full">
                <div className="flex items-center justify-between px-5 py-3 border-b border-white/10 bg-white/5">
                  <span className="text-sm font-medium text-white">{docTitle}</span>
                  <button
                    onClick={printDocument}
                    className="text-xs bg-green-500 hover:bg-green-400 text-black font-medium px-3 py-1.5 rounded-lg transition-colors"
                  >
                    Print / PDF
                  </button>
                </div>
                <div className="flex-1 overflow-y-auto p-5">
                  <pre className="text-xs text-white/60 whitespace-pre-wrap font-mono leading-relaxed">
                    {document}
                  </pre>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}